### ISSUE TITLE
Fixed positions not working in initial data in v2.0.0

### ISSUE THREAD

**Issue by rlashaw** [ogobrecht/d3-force-apex-plugin#10]
I have really enjoyed what you are providing with the D3 plugin. I am trying to learn what I can do with it so that I might take better advantage of its capabilities. I hope that you can point me to what I am doing incorrectly.

I am wanting to draw a fixed position hierarchical diagram in Apex. 
I am using the Apex d3-force-apex-plugin version 2.0.0.
All Region Attributes are empty except for Configuration Object setting which is:
     {
       "minNodeRadius": 8,
       "maxNodeRadius": 24,
       "colorScheme": "direct",
       "useDomParentWidth": true,
       "height": 800,
       "setDomParentPaddingToZero": true,
       "alignFixedNodesToGrid": true,
       "showBorder": false,
       "showLegend": false,
       "lassoMode": true,
       "zoomMode": true
     }
All Region Definition values are default or empty except for the Source which is:
     select '<data>
       <nodes ID="Manager"   LABEL="Manager"  SIZEVALUE="4"  COLORVALUE="green"  COLORLABEL="Manager"      fixed="true"  x="225"  y="100" />
       <nodes ID="App1"      LABEL="App1"     SIZEVALUE="5"  COLORVALUE="blue"   COLORLABEL="Application"  fixed="true"  x="125"  y="200" />
       <nodes ID="App2"      LABEL="App2"     SIZEVALUE="5"  COLORVALUE="blue"   COLORLABEL="Application"  fixed="true"  x="325"  y="200" />
       <nodes ID="Prod1"     LABEL="Prod1"    SIZEVALUE="2"  COLORVALUE="blue"   COLORLABEL="Environment"  fixed="true"  x="75"   y="300" />
       <nodes ID="Dev1"      LABEL="Dev1"     SIZEVALUE="2"  COLORVALUE="blue"   COLORLABEL="Environment"  fixed="true"  x="175"  y="300" />
       <nodes ID="Prod2"     LABEL="Prod1"    SIZEVALUE="2"  COLORVALUE="blue"   COLORLABEL="Environment"  fixed="true"  x="275"  y="300" />
       <nodes ID="Dev2"      LABEL="Dev1"     SIZEVALUE="2"  COLORVALUE="blue"   COLORLABEL="Environment"  fixed="true"  x="375"  y="300" />
       <nodes ID="server1"   LABEL="server1"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="50"   y="400" />
       <nodes ID="server2"   LABEL="server2"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="100"  y="400" />
       <nodes ID="server3"   LABEL="server3"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="150"  y="400" />
       <nodes ID="server4"   LABEL="server4"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="200"  y="400" />
       <nodes ID="server5"   LABEL="server5"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="250"  y="400" />
       <nodes ID="server6"   LABEL="server6"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="300"  y="400" />
       <nodes ID="server7"   LABEL="server7"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="350"  y="400" />
       <nodes ID="server8"   LABEL="server8"  SIZEVALUE="5"  COLORVALUE="red"    COLORLABEL="Server"       fixed="true"  x="400"  y="400" />
       <links FROMID="App1"  TOID="Manager"/>
       <links FROMID="App2"  TOID="Manager"/>
       <links FROMID="App1"  TOID="Prod1"/>
       <links FROMID="App1"  TOID="Dev1"/>
       <links FROMID="App2"  TOID="Prod2"/>
       <links FROMID="App2"  TOID="Dev2"/>
       <links FROMID="Prod1" TOID="server1"/>
       <links FROMID="Prod1" TOID="server2"/>
       <links FROMID="Dev1"  TOID="server3"/>
       <links FROMID="Dev1"  TOID="server4"/>
       <links FROMID="Prod2" TOID="server5"/>
       <links FROMID="Prod2" TOID="server6"/>
       <links FROMID="Dev2"  TOID="server7"/>
       <links FROMID="Dev2"  TOID="server8"/>
     </data>
     ' as single_clob_data from dual

The first issue is that the rendered diagram does to come close to the hierarchical image I expected. The nodes seem to align vertically. The second issue is that if I simply refresh the browser window (F5), the nodes continue to be drawn vertically, but in different x-axis offsets.

Please let me know if you are willing to try to provide directions. If there is a better way to communicate, I will use that. If you need more information, please let me know what would help.

I appreciate any assistance that you are willing to provide.

**Comment by ogobrecht** [comment]
Hi,

congratulations - you found a bug in v2.0.0 - this was working before - shame on me :-(

I am reworking in the moment the documentation and have to do some things, so I need some time for the official Bugfix release - I think latest next weekend it will come. 

In the meantime you can download and test a beta version of my plugin:
https://www.gobrechts.net/downloads/region_type_plugin_net_gobrechts_d3_force_2.0.1b1.sql.zip

Please let me know, if it is working for you. I tested with your data and everything is fine. Only two little things:

1. Set gridSize to 25 for your data, because you are using values in you x and y positions that can be devided by 25, but not by 50, your current (default) gridSize. If you disable and reenable alignFixedNodesToGrid in the customization wizard, then some of your nodes will move away because they try to find the next grid position - and this position is 25 pixel away from their current positions. With a gridSize of 25  the nodes are not moving, because the grid matches the current positions.
2. Try to set set pinMode to true - after you are releasing some or all nodes you can then rearrange the nodes and they will be fixed again when you drag they around.

Kind regards, Ottmar

**Comment by rlashaw** [comment]
I have downloaded your beta version. It works really well. THANKS! I set the gridSize to 25 and it does what you would expect. I played with the pinMode and it does what you said as well. This is a really nice plugin. I will download the official version when you release it.

New question. Do you have any thoughts on adding save the SVG to PNG, GIF, JPG, or PDF?

**Comment by ogobrecht** [comment]
Hi,

thank you for your feedback :-)

Regarding your question about saving the SVG: Images like PNG, GIF, JPG and PDF are not so easy to export direct from the browser with javascript - see alsp this discussion:
http://stackoverflow.com/questions/3316193/take-screenshot-of-browser-via-javascript-or-something-else

But I will think about to provide some possibility to save the existing SVG, this seems to be a good idea - thank you.

Kind regards, Ottmar

**Comment by ogobrecht** [comment]
Fixed with new release 2.0.1
