### ISSUE TITLE
Not able to install/import in Apex 5.0.1 and ORacle 11.2 XE

### ISSUE THREAD

**Issue by Samraw003** [ogobrecht/d3-force-apex-plugin#11]
Hi,

I am not able to install the Demo ZIP file as a plug-in. My environment is Apex 5.0.1 and Oracle XE 11.2.

I receive following error as I try to install it. Please note that file is getting imported but not able to install.

"File is not a valid Application Express plug-in export file."

Thanks

Sammeer

**Comment by ogobrecht** [comment]
Hi Sammeer,

Do you meen the file https://gobrechts.net/downloads/d3-force-apex-plugin-demo-app.zip?

This is the demo application, which is installed on apex.oracle.com - you have to install this as a application, not a plugin. The plugin is integrated in the demo app.

Please extract the sql install file from the zip archive before you upload it to your APEX instance.

Best regards
Ottmar

**Comment by Samraw003** [comment]
Hi Ottmar,

Thanks a lot. It works wonderfully well!

Regards

*Sammeer*
