### ISSUE TITLE
tooltips not showing correctly

### ISSUE THREAD

**Issue by pocelka** [ogobrecht/d3-force-apex-plugin#12]
I've checked your apex plugin in version 5.0.3.00.03 and provided our data via the XML notation.
[data.zip](https://github.com/ogobrecht/d3-force-apex-plugin/files/361764/data.zip)

I'm using the following attributes:
{
  "useDomParentWidth": true,
  "lassoMode": false,
  "showLabels": false,
  "zoomMode": true,
  "pinMode": true,
  "colorScheme": "direct",
  "height": 650,
  "debug": true
}

Once page is loaded tooltips are not disaplayed. They are displayed only when I click on "customize me" link, setup show labels = true, and immediatelly disable the labes with show labels = false.

**Comment by ogobrecht** [comment]
Hi pocelka,

congratulation - you found a bug. This must be a initialization problem - you can see many errors in the browsers JavaScript console. The errors disappear, if you set showLabels to true. I will fix this at the weekend.

In the meantime you can workaround this by setting showLabels to true in the "Region Attributes > Configuration Object and add a css rule under "Region Attributes > Custom Styles": `.net_gobrechts_d3_force text.label{ display: none; }`.

One comment to your query: under the nodes you have multiple times the node with the ID 800. I corrected your query as follows (no formatting at the moment, sorry) - I don't know your data, so please think about, if the additional "distinct" can be permanent solution:

```sql
WITH nodes_base as (select distinct inv.object_id                         as id,
                                    inv.proc_id                           as label,
                                    1000                                  as sizevalue,
                                    'green'                               as colorvalue,
                                    --regexp_substr(proc_id, '[^.]+', 1, 1)  as colorlabel,
                                    --regexp_substr(proc_id, '[^.]+', 1, 1) || chr(10) ||
                                    inv.proc_id || '<br/>'/*chr(10)*/ ||
                                    'Start: 13.07.2016 16:00:00' || '<br/>'/*chr(10)*/ ||
                                    'End: 13.07.2016 16:15:00'            as infostring --, following attributes must be lowercase, otherwise they are useless (node attributes are case sensitive and these three are native d3 ones)--> see also https://gobrechts.net/wiki/projects/d3-force-apex-plugin#node-attributes
                                  --  'true'                                as "fixed",
                                  --  nvl(rel.timeline,0)                   as "x",
                                  --  nvl(rel.row_position,0)               as "y"
                     from cfg_plef_object_rel  rel,
                          cfg_plef_object_inv  inv
                    where 1 = 1
                      and inv.luw_type = 'CA'
                      and inv.object_id = rel.object_id(+)
                      and inv.luw_type = rel.luw_type(+)
                      and rel.active_flg(+) = 'Y'
                    order by inv.object_id), 
   --> START YOUR NODES QUERY HERE
   nodes AS (SELECT XMLELEMENT("nodes", xmlattributes( id,
                                                       label,
                                                       sizevalue,
                                                       colorvalue,
                                                       infostring --,
                                                      -- "fixed",
                                                      -- "x",
                                                      -- "y"
                                                     )) AS xml_nodes
               from nodes_base
   --< STOP YOUR NODES QUERY HERE
            ),
   --> START YOUR LINKS QUERY HERE
   links AS (SELECT XMLELEMENT( "links", xmlattributes(rel.pred_object_id     AS fromid,
                                                       rel.object_id          AS toid,
                                                       'solid'                as style,
                                                       --'black'                as color,
                                                       rel.pred_object_id || ' -> ' || rel.object_id as infostring) ) AS xml_links
            FROM cfg_plef_object_rel rel
            order by rel.pred_object_id,rel.object_id
   --< STOP YOUR LINKS QUERY HERE
            )
SELECT 
   XMLSERIALIZE( DOCUMENT( XMLELEMENT("data",
                                      ( SELECT XMLAGG( xml_nodes ) FROM nodes ),
                                      ( SELECT XMLAGG( xml_links ) FROM links ) ) ) INDENT ) AS single_clob_result
FROM DUAL
```

You can find a running demo here: https://apex.oracle.com/pls/apex/f?p=78310:4

Here is the demo app for you own environment: [f78310.sql.zip](https://github.com/ogobrecht/d3-force-apex-plugin/files/362367/f78310.sql.zip)

Best regards
Ottmar

**Comment by pocelka** [comment]
Thank you, it works with this workaround.

The thing is that I'm just starting with apex, looking what we can do with it, and how we could adapt it to our purposes. So most of the work I done is trial / error :)

**Comment by ogobrecht** [comment]
Hi pocelka,

the bugfix release for your issue is out. Hope you find no new bugs ;-)

Best regards
Ottmar
