### ISSUE TITLE
enhancement: configurable area for tooltip

### ISSUE THREAD

**Issue by pocelka** [ogobrecht/d3-force-apex-plugin#13]
Would it be possible to have configurable tool tip area size?

If you check issue #12, you can see that the area is simply not enough for more complex tool tips.

**Comment by ogobrecht** [comment]
Hi pocelka,

this is possible in the current implementation. Simply add under the "Region Attributes > Custom Styles" the following rule:

```css
.net_gobrechts_d3_force_tooltip { width: 300px !important; }
```

See also my answer for #12 - you find there a link to a running demo and also the sample app itself for your own environment.

If you want to know which styles are currently in use, please ask your browser tools :-)  or have a look in the plugin itself by downloading and inspecting the css file.

Best regards
Ottmar
