### ISSUE TITLE
complex network graph - not rendering nodes

### ISSUE THREAD

**Issue by pocelka** [ogobrecht/d3-force-apex-plugin#14]
I have a complex network graph. Once rendered on the page, some nodes are not correctly rendered. I can see links going to the nodes but node itself is missing (it is not possible to do mouse over, or even drag & drop node).

[data.zip](https://github.com/ogobrecht/d3-force-apex-plugin/files/361775/data.zip)

**Comment by ogobrecht** [comment]
Hi pocelka,

this is possibly a data error - see my comments on #12 - your query selects multiple times the node with the ID 800 (and possible other ID's). I set a distinct on the nodes query and the problem should be gone. 

Please check #12 and let me know, if I am right, so I can close this ticket

Best regards
Ottmar

**Comment by pocelka** [comment]
You are correct, node with ID 800 and few more were selected multiple times. When I was building a query I forgot one major aspect, that your plugin and our existing functionality written in C# are different. 

We have two tables *INV which holds "nodes" and *REL which holds relation + position in the graph. And of course when joined together it provides duplicates as one node can be parent to several children. It's actually different approach in plugin which I did not consider.

I'm investigating how we could move our current functionality from this C# application to APEX.

We can close this ticket as it is not a bug, but human stupidity.
