### ISSUE TITLE
Manual Corrdinates usage

### ISSUE THREAD

**Issue by DoctorTelms** [ogobrecht/d3-force-apex-plugin#16]
When using Node D3 attributes 
--, 'true'       AS "fixed"       -- optional | fixed, x and y are native
     --, 100          AS "x"           -- optional | D3 attributes, they must be
     --, 100          AS "y"           -- optional | lowercase

The links are not rendered from/to the nodes, they are nor aligned on the same alignment of the nodes inside chart frame.
![screen_1](https://cloud.githubusercontent.com/assets/23385645/20187472/4a3f186c-a76c-11e6-8ae7-4d2c93d4c57f.png)

some help please ? have tried several options..

**Comment by ogobrecht** [comment]
Hi, 

can you please provide the resulting XML from your query and your configuration object or setup a testcase on apex.oracle.com. You can provide me the login data via orclapex@gobrechts.net.

Thank you and kind regards
Ottmar

**Comment by ogobrecht** [comment]
Hi,

how are you?

I created a [playground][1] in my online demo app and was able to create your graph (see also issue #17):

![image](https://cloud.githubusercontent.com/assets/10425445/20684062/b8d823b8-b5ae-11e6-853d-0aef2af01574.png)

I used the follwowing XML sample data:

```html
<data>
  <nodes ID="1" LABEL="1" COLORVALUE="1" SIZEVALUE="1" fixed="true" x="100" y="100"/>
  <nodes ID="2" LABEL="2" COLORVALUE="1" SIZEVALUE="1" fixed="true" x="300" y="200"/>
  <nodes ID="3" LABEL="3" COLORVALUE="1" SIZEVALUE="1" fixed="true" x="100" y="300"/>
  <nodes ID="4" LABEL="4" COLORVALUE="1" SIZEVALUE="1" fixed="true" x="120" y="300"/>
  <nodes ID="5" LABEL="5" COLORVALUE="1" SIZEVALUE="1" fixed="true" x="140" y="300"/>
  <nodes ID="6" LABEL="6" COLORVALUE="1" SIZEVALUE="1" fixed="true" x="160" y="300"/>
  <nodes ID="7" LABEL="7" COLORVALUE="1" SIZEVALUE="1" fixed="true" x="180" y="300"/>
  <links FROMID="1" TOID="3"/>
  <links FROMID="1" TOID="4"/>
  <links FROMID="1" TOID="5"/>
  <links FROMID="1" TOID="6"/>
  <links FROMID="1" TOID="7"/>
  <links FROMID="2" TOID="3"/>
  <links FROMID="2" TOID="4"/>
  <links FROMID="2" TOID="5"/>
  <links FROMID="2" TOID="6"/>
  <links FROMID="2" TOID="7"/>
</data>
```

The used graph options were the standard ones of the playground:

```javascript
{
  "useDomParentWidth": true,
  "setDomParentPaddingToZero": true,
  "showBorder": false,
  "lassoMode": true,
  "zoomMode": true,
  "debug": true
}
```

Which version you are using? The current one is 2.0.2. Are you using the APEX plugin or the standalone implementation in a HTML page? Please have a look at the [project documentation][2] and let me know, if I can improve something or what is missing or wrong.

[1]: https://apex.oracle.com/pls/apex/f?p=18290:4
[2]: https://gobrechts.net/wiki/projects/d3-force-apex-plugin

Hope, I could help you a little bit.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi,

I think you should check, if you deliver distinct data. Looks like you have multiple nodes with the same ID in your query/data. Again, please have also a look at issue #17 - your problem seems to be the same.

Please let me know, if your graph is then working - if not provide me sample data, so that I can have a deeper look at the problem.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi,

how are you? Any news? Can I close this Issue?

Best regards
Ottmar

**Comment by DoctorTelms** [comment]
Hi ottmar.

First of all, sorry for the late reply.. ( gonna be a father... )

Tou van close the issue. I resolveu the problemas via workaround. Many
thanks for tour insight and help.

Best regards
Telmo Fernandes.

Em 23/01/2017 21:29, "Ottmar Gobrecht" <notifications@github.com> escreveu:

**Comment by ogobrecht** [comment]
Hi Telmo,

no problem, this is the best reason you can have :-)

Congratulation and all the best for you and your family
Ottmar
