### ISSUE TITLE
Using the plugin as a Directed Graph

### ISSUE THREAD

**Issue by rlegge** [ogobrecht/d3-force-apex-plugin#17]
Hi, Apologies first of all. This isn't probably an issue, but I can't find anywhere where there is a support forum, or a way to raise a question. (Please advise)

I'm trying to use the plugin as a Directed Graph. i.e. entities (records) have multiple relationships with other records.

For example, date this dataset below. Im trying to visualise the relationships with other records. Im expecting the graph to show 6 items. (1 - 6), then the links between them. Is this possible.

ID	LINK_ID
1	2
1	3
1	4
2	1
2	5
2	6
3	1
4	5
5	4
5	2
6	2

Instead I get the following:

![image](https://cloud.githubusercontent.com/assets/6523093/20621883/0a160900-b309-11e6-96ed-9ca6dddbc55a.png)

Thanks
Richard

**Comment by ogobrecht** [comment]
Hi Richard,

I created a [playground][1] in my online demo app and I was able to create a working graph. No idea, what is wrong with your environment - do you use the latest version (2.0.2) of the plugin? Or you forgot mandatory attributes?

![image](https://cloud.githubusercontent.com/assets/10425445/20677641/fbba6a80-b593-11e6-969c-121be8fd6ca1.png)

Please try out the following data in the  [playground][1]:

```javascript
{
  "data": {
    "nodes": [
      { "ID":"1", "LABEL":"1", "COLORVALUE":"1", "SIZEVALUE":1 },
      { "ID":"2", "LABEL":"2", "COLORVALUE":"1", "SIZEVALUE":1 },
      { "ID":"3", "LABEL":"3", "COLORVALUE":"1", "SIZEVALUE":1 },
      { "ID":"4", "LABEL":"4", "COLORVALUE":"1", "SIZEVALUE":1 },
      { "ID":"5", "LABEL":"5", "COLORVALUE":"1", "SIZEVALUE":1 },
      { "ID":"6", "LABEL":"6", "COLORVALUE":"1", "SIZEVALUE":1 }
    ],
    "links": [
      { "FROMID":"1", "TOID":"2" },
      { "FROMID":"1", "TOID":"3" },
      { "FROMID":"1", "TOID":"4" },
      { "FROMID":"2", "TOID":"1" },
      { "FROMID":"2", "TOID":"5" },
      { "FROMID":"2", "TOID":"6" },
      { "FROMID":"3", "TOID":"1" },
      { "FROMID":"4", "TOID":"5" },
      { "FROMID":"5", "TOID":"4" },
      { "FROMID":"5", "TOID":"2" },
      { "FROMID":"6", "TOID":"2" }
    ]
  }
}
```

or

```html
<data>
  <nodes ID="1" LABEL="1" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="2" LABEL="2" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="3" LABEL="3" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="4" LABEL="4" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="5" LABEL="5" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="6" LABEL="6" COLORVALUE="1" SIZEVALUE="1"/>
  <links FROMID="1" TOID="2"/>
  <links FROMID="1" TOID="3"/>
  <links FROMID="1" TOID="4"/>
  <links FROMID="2" TOID="1"/>
  <links FROMID="2" TOID="5"/>
  <link,s FROMID="2" TOID="6"/>
  <links FROMID="3" TOID="1"/>
  <links FROMID="4" TOID="5"/>
  <links FROMID="5" TOID="4"/>
  <links FROMID="5" TOID="2"/>
  <links FROMID="6" TOID="2"/>
</data>
```

Your SQL Query must produce the XML or JSON above as a single CLOB result - for XML you can have a look at the [example queries][2] in the [project documentation][3].

You can download the demo app [here][4] and install it in your own workspace.

Hope, I could help you.

Best regards
Ottmar

[1]: https://apex.oracle.com/pls/apex/f?p=18290:4
[2]: https://gobrechts.net/wiki/projects/d3-force-apex-plugin#example-queries
[3]: https://gobrechts.net/wiki/projects/d3-force-apex-plugin
[4]: https://gobrechts.net/downloads/d3-force-apex-plugin-demo-app.zip

**Comment by rlegge** [comment]
Thanks Ottmar,

I didn't realise, that the node data needs to be unique, and the links
non-unique. Now I tried with distinct on the first query it works fine.

I have another question. My link label is quite long. How do I split it
across two lines?

Kind regards
Richard

p.s. awesome plug-in by the way.

**Comment by ogobrecht** [comment]
Hi Richard,

SVG 1.1 does not support textareas - so this is not very easy to implement for all browsers. See also this entry on [stackoverflow][1].

[1]: http://stackoverflow.com/questions/16701522/how-to-linebreak-an-svg-text-within-javascript

You can use the INFOSTRING attribute for this - it will be shown as a tooltip. You can configure the tooltip position in the graph configuration. Please try this example and hover the node 1 with your mouse:
 
```html
<data>
  <nodes ID="1" LABEL="1" COLORVALUE="1" SIZEVALUE="1" INFOSTRING="A very long label that display in a tooltip :-)"/>
  <nodes ID="2" LABEL="2" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="3" LABEL="3" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="4" LABEL="4" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="5" LABEL="5" COLORVALUE="1" SIZEVALUE="1"/>
  <nodes ID="6" LABEL="6" COLORVALUE="1" SIZEVALUE="1"/>
  <links FROMID="1" TOID="2"/>
  <links FROMID="1" TOID="3"/>
  <links FROMID="1" TOID="4"/>
  <links FROMID="2" TOID="1"/>
  <links FROMID="2" TOID="5"/>
  <links FROMID="2" TOID="6"/>
  <links FROMID="3" TOID="1"/>
  <links FROMID="4" TOID="5"/>
  <links FROMID="5" TOID="4"/>
  <links FROMID="5" TOID="2"/>
  <links FROMID="6" TOID="2"/>
</data>
```

Hope this solution is ok for you - a nice side effect is that your graph is not spoiled with to many text.

And many thanks for the comment "awesome plug-in by the way" - this helps to stay motivated :-)

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Richard,

I created a [comment][1] in the project documentation for the need of distinct data. If you have no further questions please let me know or close this issue by yourself.

Best regards
Ottmar

[1]: https://gobrechts.net/wiki/projects/d3-force-apex-plugin#example-queries

**Comment by rlegge** [comment]
Hi Ottmar,

That's fine if you want to go ahead and close it.

Many Thanks
Richard
