### ISSUE TITLE
apex 5.1, syntax error

### ISSUE THREAD

**Issue by KiralyCs** [ogobrecht/d3-force-apex-plugin#18]
I've used your plugin with apex 5.0, everything was all right. Till friday, then there was an upgrade (oracle cloud workspace), and now every chart (the example too) throws an error and can't load, the page and the plugin stops at loading:
   Error: Syntax error, unrecognized expression: #.
Please help, I don't know where to fix it.
Attached some screenshots.
![screen1](https://cloud.githubusercontent.com/assets/24504806/21079350/2565419c-bf90-11e6-955c-f2e9f3ae98b6.png)
![screen2](https://cloud.githubusercontent.com/assets/24504806/21079351/2599e140-bf90-11e6-8e45-c91b968d52cc.png)

**Comment by ogobrecht** [comment]
Hi,

it's nice to hear, that you have already APEX 5.1 running on apex.oraclecorp.com ;-)

My plugin uses jQuery only to provide the graph events to the APEX dynamic actions - so it is not clear for me, if your errors are related to the plugin itself. To find this out please enter the debug mode in the application builder toolbar - these force the system to load the uncompressed JavaScript libs, which is also supported by my plugin. Then have a look in your browser console if you can see any details about the rootcause of your errors.

Do you have any dynamic actions configured for the graph or are you using the graph JavaScript API? If so, please try first to deactivate the dynamic actions and find out, if then the graph is starting.

Do you see any chance, that I can have a deeper look at your problem? May be a remote desktop session?

Hope, I could help a little bit.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi again,

do you have configured in the region source the attribute "Page Items to Submit"? If not, please try to fill anything here and let me know, if it is working for you.

Best regards
Ottmar

**Comment by KiralyCs** [comment]
Hi, your second guess was right :)
Added a hidden item, listed it at the page items to submit, and everything loaded fine.
Without that, debugged the page, attached the results.
If everything loads well, there is two debug message, a normal and an ajax one. Attached these too.
Will you fix this thing, or it's necessary, to put at least one item into that list?
Thanks

[debug.zip](https://github.com/ogobrecht/d3-force-apex-plugin/files/645692/debug.zip)
![screen1](https://cloud.githubusercontent.com/assets/24504806/21096407/14de1184-c060-11e6-8766-e97fee730289.png)

**Comment by ogobrecht** [comment]
Hi,

I will fix this. Unfortunately I have currently no access to my 4.2.6 dev instance to deliver a APEX 4.2 compatible bugfix release. But I tried out something on apex.oracle.com. You can download the bugfix preview [here](http://gobrechts.net/downloads/region_type_plugin_net_gobrechts_d3_force_2.0.3_apex_5_only.sql.zip).

Please let me know, if this is working for you under 5.1 without configured "Page Items to Submit". I will then create tomorrow the final (APEX 4.2 compatible) bugfix and release it during the evening (after 20:00 CET).

Best regards
Ottmar

P.S.: My second guess comes from Carsten Czarski, probably a colleague of you :-)

**Comment by KiralyCs** [comment]
Checked out in my simple test app, works like a charm, without any "Page Items to Submit". Thanks! I'm waiting for the final version to fix the main app.

**Comment by ogobrecht** [comment]
Thank you for your quick test :-)

The final version will come tomorrow evening...

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi,

the bug fix release is out, you can download it under https://github.com/ogobrecht/d3-force-apex-plugin/releases/latest

Best regards
Ottmar

**Comment by KiralyCs** [comment]
Thank you, problem solved!
