### ISSUE TITLE
How to manage predefined node positions

### ISSUE THREAD

**Issue by katiakholodkova** [ogobrecht/d3-force-apex-plugin#19]
Hi,
I need your help - I'm trying to find a way how to save predefined node positions every time when I change them on the chart by dragging a node (or adding one). In other words I want the nodes stay where I left them, with no motion.
Are there any ways to do that?
Sorry if I missed this in previous comments.
Thank you !
Ekaterina

**Comment by ogobrecht** [comment]
Hi Ekaterina,

- customize your graph by clicking the "customize me" link
- under nodes enable dragMode and pinMode
- when you are done, copy the current node positions
- go to the region in the application builder (if you are using the APEX plugin) and paste the current positions into the corresponding field
- save the region options

Your node positions should now be stable after the reload of the page.
 
<img width="1139" alt="d3-force-screenshot" src="https://cloud.githubusercontent.com/assets/10425445/22184785/b0ca2878-e0d9-11e6-8455-9d0499add317.png">

Hope I could help you.

Best regards
Ottmar

**Comment by katiakholodkova** [comment]
Hi Ottmar,
 thank you very much for your reply, it works!
Thank you again!
Ekaterina

**Comment by ogobrecht** [comment]
Hi Ekaterina,
nice to hear, that it is working for you.
Best regards
Ottmar
