### ISSUE TITLE
Is there an application demo / app, ready to download and install ?

### ISSUE THREAD

**Issue by etaygudai** [ogobrecht/d3-force-apex-plugin#21]
Hello Ottmar,

Thank you for this great opportunity - it seems like exactly what I looked for.
**Do you have any ready to install app / page, so we can start play around ?** ( didn't find it in source code ) 
Apprciated.
Etay G

**Comment by ogobrecht** [comment]
Hi etaygudai,

do you want to use it as an Oracle APEX plugin or standalone in an HTML page? For Oracle APEX there is an online sample app: https://apex.oracle.com/pls/apex/f?p=18290

I am currently improving some things, if you only want to play around first, then you can also check out the dev branch. You can find there under the `server` sub directory an example.html file and under the `docs` directory an improved API documentation - this will be later on served under http://ogobrecht.github.io/d3-force-apex-plugin.

In the README of the master are some links listed - one goes to the old [documentation in my (old) wiki](https://gobrechts.net/wiki/projects/d3-force-apex-plugin#getting-started) - but it should be a good starting point until the dev branch is merged into the master branch. You see - many things are changing in the moment - hope you find it useful anyway.

If you have any further question, please let me know.

Best regards
Ottmar

**Comment by etaygudai** [comment]
*Thank you Ottmar for your detail answer .*

1. I would like to use this as an Apex plugin, yet, I was looking for a
ready to install app / page containing an example that is based on plugin
already ( plugin was installed successfully in my apex 5.1 ) that's because
I didn't manage to activate it as both Apex plugin or using the standalone
version.

2. Also checked example.html that comes in d3-force-apex-plugin-2.0.3 (
tried to activate it as standalone sample with no success  ) also after
changing the pathes for css / js in example.html due to 2.0.3 version fix.
I also get a blank page.

*My Questions are : *
1. What I am missing in standalone sample ?

2. Is there a ready app / page example I can just install on my env and
test ? ( familiar with https://apex.oracle.com/pls/apex/f?p=18290 - thank
you)

Regards
Etay G

**Comment by ogobrecht** [comment]
Hi,

sorry for the corrupted example.html - obviously I missed something after the last hot fix for APEX 5.1.

So, if you plan to use it as a plugin, then simply use the link provided inside the demo app :-)
<img width="955" alt="d3plugin" src="https://user-images.githubusercontent.com/10425445/29088448-5ebb6a60-7c79-11e7-9bfd-a9cac3f61e88.png">

I am currently reworking the demo app with the universal theme, but this is not finished yet. You will find out that there is no special thing at all for standard use of the plugin. Like with a report you have to provide a query with needs a special output in XML or JSON format - please consult the inline help for the region query in the APEX application builder or the API documentation here (links are also provided in the demo app): https://gobrechts.net/wiki/projects/d3-force-apex-plugin#example-queries

If you are working under the Oracle 11G express edition I recommend the XML format - if you look in detail to the example query you will find out that you have to deliver only some sort of standard selects. I also recommend to check your query in your preferred SQL tool before you provide it in the region source.

If you have any question regarding the options in the customization wizard please follow the links provided to the API description:

<img width="684" alt="d3plugin2" src="https://user-images.githubusercontent.com/10425445/29089015-3c586d5e-7c7b-11e7-83d9-6c258f535950.png">

As you can see - there is some information - you have only to pick it up and read carefully ;-)

Hope this helps, best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Etay,

how are you? I am paused my work on this plugin and the new demo app for a while during the autumn, but the winter is coming and some more free time with it. Are you ok with the informations provided until now? Can we close this issue or do you have still questions?

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Etay,

any news? Can I close the issue?

Best regards
Ottmar

**Comment by ogobrecht** [comment]
No response from user. Issue closed.
