### ISSUE TITLE
Change from circle to rectange with inside label

### ISSUE THREAD

**Issue by BirtheG** [ogobrecht/d3-force-apex-plugin#28]
Hallo Ottmar,
many thanks for the plugin for the D3 Force diagram. I would like to use it in order to display dependencies between documents.
It is possible to change from circle rectangle using inside labels?

Many thanks,

Birthe

**Comment by ogobrecht** [comment]
Hi Birthe,

sorry for my late response - I‘m currently on vacation.

The plug-in supports only circles - many calculations and options are specific for circles. Sorry.

But I think you can find D3 examples with rectangles and inline labels - simply google for it. If you have not so many feature wishes it should be easy to create a dedicated implementation for your specific use case (depending on your JavaScript knowledge, of course).

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Old question. Issue closed.
