### ISSUE TITLE
Using the plugin on new Release 18.1 (5.2 basically) has 404 error for CSS and JS files

### ISSUE THREAD

**Issue by Ignacius68** [ogobrecht/d3-force-apex-plugin#29]
After upgrading APEX to release 18.1 (which I'm told is basically 5.2), there are 3 files showing a 404 error.  Has this been seen before?  Is there some server cache clearing or restarting that's supposed to happen?

Files "missing": d3-force-2.1.2.css, d3-force-2.1.2.min.js, d3-3.5.6.min.js

With these files having a 404 error, the graph object is not defined.  Any information appreciated!

**Comment by Ignacius68** [comment]
Found out there is a "validation" script for APEX configurations that remedied the issue.  All better!

**Comment by ogobrecht** [comment]
Hi Ignacius68,

thank you for closing the issue :-)

Kind regards
Ottmar

**Comment by Ignacius68** [comment]
Hi,

You're quite welcome!

Absolutely loving the plugin!  Is the GitHub the best place to make
feature requests?

-Ignacius

**Comment by ogobrecht** [comment]
Hi Ignacius68,

yes, other people could see then the feature request also and comment on it.

Nice to hear that you find the plugin useful - such comments keep me motivated :-)

Kind regards
Ottmar
