### ISSUE TITLE
APEX plug-in: Sample data is rendered before live data

### ISSUE THREAD

**Issue by ogobrecht** [ogobrecht/d3-force-apex-plugin#32]
When using the APEX plug-in sample data is rendered before live data is loaded via AJAX call. This is not always the case - for an example the sample app does not has this issue, one of my Universal Theme apps has it. Need some investigation to figure out what the problem is.

**Comment by Ignacius68** [comment]
Do let me know if I can assist from my side.   :)

**Comment by Ignacius68** [comment]
Hi Ottmar!

Didn't mean to go radio silent.  I've been working to get a stable version of my app moved up to a higher environment, so I can install this beta in dev.  Bear with me.  I'll be able to test within a couple weeks.

- Ig

**Comment by ogobrecht** [comment]
Hi Ignacius,

no problem, simply come back to me when you are done with testing. And thank you again for your help.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Ignacius,

I will have a look at it on the weekend. Thanks for the testing so far. 

- I think some trouble come from a hidden tab container - good finding, was not in my focus that a container could be hidden some times...
- The rectangle errors come from aligning of all the SVG containers for zoom and pan, seems also related to the hidden container, has nothing to do with your data, I will see,,,
- If you define a split character, than the width value is ignored... at least this was the idea...

You will hear from me. Best regards
Ottmar

**Comment by Ignacius68** [comment]
Wanted to also call out the re-centering after every render.  With a large graph where you're zoomed into a particular part, you don't want the view moving unexpectedly.  This re-centering just started with this version, I double checked 2.2.2 and there's no center at the end of a render.

Thanks for working on this!  Absolutely loving the plugin.  :)

**Comment by ogobrecht** [comment]
Hi Ignacius,

sorry, my weekend was not going as expected. I need some days more to work on the issues. You are absolutely right: when an end user has the ability to zoom, the recentering should be ignored  after force end, even it is switched on. The zoom mode should have precedence.

You will hear from me, best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Igancius,

beta 2 is available. Please try it out. Hopefully all your errors are gone and you find no new ones :-)

Best regards
Ottmar

**Comment by Ignacius68** [comment]
Hi Ottmar,

I got the new Beta 2 installed and tested, and I can't find any more bugs!  All the original goodies check out as well.

1. JS errors are all gone!
2. Zoom and Pan continue to work no matter how often I switch Tabs and hide the graph.
3. No more recentering with zoomtofit = false.

Thanks much!  I'll look forward to the release so I can start promoting up beyond QA.  :)

- Ig

**Comment by ogobrecht** [comment]
Hi Ignacius,

the release 3.0.0 is out. Thank you very much again for your help!

I had to fix a small bug regarding the legend - so please update to the current version.

Best regards\
Ottmar
