### ISSUE TITLE
Enhancement Request: Add a delimiter option to split label strings

### ISSUE THREAD

**Issue by Ignacius68** [ogobrecht/d3-force-apex-plugin#33]
From working on very "dense" graph presentations, I've found the labeling to be a bit challenging.  In some cases, depending on naming choices, the nodes end up with long labels.

The width-based split works to a degree, until it starts breaking apart one of the "parts" of the label.  For instance, a Component-level node graph has the nodes named as "[System Layer] : [Component]".  To accommodate use cases like this, I am requesting a delimiter split option.  My recommendation is a 2 character string for the split, which would allow you to still use punctuation within the labels, and have a reliable split mechanism.  Further, I would recommend a double colon ("::") as the default delimiter string.

This allows a "multi-part" labeling strategy, as well as the existing "paragraph" labeling strategy.

The logic for a delimiter split "should" be easier, as it's presumably a javascript `str.split('::');`, for instance.

As to controlling whether it's width or delimiter split, my best idea is to add a drop down option, either option could be the default (whichever you'd prefer to encourage).  Another possibility is to have the default as delimiter split, and you clear the delimiter string to perform width split.  Drop down choice "feels" easier on the brain to understand.  :)

- Ignacius

**Comment by ogobrecht** [comment]
Implemeted with v3.0.0
