### ISSUE TITLE
Images blurry in chrome and edge

### ISSUE THREAD

**Issue by chrizwagner** [ogobrecht/d3-force-apex-plugin#43]
Hello! 

When I fill the cycles with images, the images blurry, using google-chrome or the edge-browser. In Firefox or IE, the images are displayed correctly.

Best regards
Chriz

**Comment by ogobrecht** [comment]
Hi Chriz,

I analyzed the problem and found a possible workaround for it. Need time to look deeper and implement it. I will come back to you in the next few days.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Chriz,

I have published the bugfix release 3.1.1. Please check, if it is also working for you.

Best regards
Ottmar
