### ISSUE TITLE
Link labels: Long texts are clipped on both sides when they are too long - should only be clipped at the end

### ISSUE THREAD

**Issue by ogobrecht** [ogobrecht/d3-force-apex-plugin#49]
See here for some help: https://alligator.io/svg/textpath/

Note: Issue was opened for @apex-michael

**Comment by apex-michael** [comment]
**Chrome Browser specific issue.**
Hi Ottmar, now that more people are using it, we have seen a browser specific issue with this.  In Firefox  (101.0.1 (64-bit)) all works fine. But in Chrome (103.0.
[Chrome Browser issue.pdf](https://github.com/ogobrecht/d3-force-apex-plugin/files/9038593/Chrome.Browser.issue.pdf)
[Chrome Browser issue.pdf](https://github.com/ogobrecht/d3-force-apex-plugin/files/9038598/Chrome.Browser.issue.pdf)
5060.66 (Official Build) (64-bit)) the label for the link is detached and displays in top left corner, if it is clipped while being in the angle of -PI/2 to PI/2 see attached description.

**Comment by ogobrecht** [comment]
Hi Michael,

sorry for my very late response. I need a little bit of time to dig into the issue. Thank you for the detailed issue description. I will you keep updated.

Best regards
Ottmar

**Comment by apex-michael** [comment]
Thanks Ottmar,

Really appreciate that.

In a week or two most of the people will have acces to see the graphs, so I assume at least some will use chrome.

As I said, really appreciate your effort on this.

Best Regards

Michael

On 21 Jul 2022, at 20.15, Ottmar Gobrecht ***@***.***> wrote:

﻿

Hi Michael,

sorry for my very late response. I need a little bit of time to dig into the issue. Thank you for the detailed issue description. I will you keep updated.

Best regards
Ottmar
