### ISSUE TITLE
No node shown if there is only one record return

### ISSUE THREAD

**Issue by wfg2513148** [ogobrecht/d3-force-apex-plugin#9]
Hi,

I try the sample data (using emp table) and it's fine. 
However, when I delete all records of emp table except "KING" (root node) and refresh the graph, no result is shown. 

It seems like a bug. Please kindly check it.

Best Regards,
Kenny Wang

**Comment by ogobrecht** [comment]
Hi Kenny,

I tried to provide only one node as a XML string and get the error "unable to convert XML string". With two nodes I have no problem. I use a third party lib for converting XML data - so I have to check there for a error with only one node. Do you get also this error message (rendered as a single node)?

If not, please provide me your XML or JSON object from your SQL query.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Kenny,

the new release 2.0.0 is out, which fixes this problem. Please test, if it is also working for you.

Best regards
Ottmar
